name: TraxonUtils
version: ${project.version}
main: de.traxonlp.Main
api-version: 1.18
authors: [ Traxon_LP ]
description: Utility Plugin from Traxon_LP
website: https://github.com/traxonLp

commands:
    about:
        description: Shows the Plugins Autor.
    broadcast:
        description: Broadcasts your Message! /broadcast <message>
    wipe:
        description: Clears Player's Inventory and Enderchest, will set XP Level to 0. /wipe <player>
    tuversion:
        description: Shows the Plugin Version.
    lag:
        description: Shows Server TPS and Lag
    cc:
        description: Clears the chat.